"""images table

Revision ID: db70463ff371
Revises: e9de7ebe5f1f
Create Date: 2020-01-15 21:43:34.130914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db70463ff371'
down_revision = 'e9de7ebe5f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_column('image', 'timestamp')
    # ### end Alembic commands ###
